/**
 * Códigos de país y subdivisiones compartidos por los adaptadores de
 * proveedores. Bridge usa ISO 3166-1 alpha-3 y la subdivisión como código
 * (ej. BOL / "L"); Tazapay usa alpha-2 y el estado como texto (BO / "La Paz").
 *
 * GENERADO desde BridgeCustomerService.ALPHA2_TO_ALPHA3 y
 * frontend_guira_staff/lib/bridge-constants.ts (COUNTRY_SUBDIVISIONS).
 * Si se agrega un país al formulario, agregarlo también aquí.
 */
export const ALPHA2_TO_ALPHA3: Readonly<Record<string, string>> = {
  AD: 'AND',
  AE: 'ARE',
  AF: 'AFG',
  AG: 'ATG',
  AI: 'AIA',
  AL: 'ALB',
  AM: 'ARM',
  AO: 'AGO',
  AQ: 'ATA',
  AR: 'ARG',
  AS: 'ASM',
  AT: 'AUT',
  AU: 'AUS',
  AW: 'ABW',
  AX: 'ALA',
  AZ: 'AZE',
  BA: 'BIH',
  BB: 'BRB',
  BD: 'BGD',
  BE: 'BEL',
  BF: 'BFA',
  BG: 'BGR',
  BH: 'BHR',
  BI: 'BDI',
  BJ: 'BEN',
  BL: 'BLM',
  BM: 'BMU',
  BN: 'BRN',
  BO: 'BOL',
  BQ: 'BES',
  BR: 'BRA',
  BS: 'BHS',
  BT: 'BTN',
  BV: 'BVT',
  BW: 'BWA',
  BY: 'BLR',
  BZ: 'BLZ',
  CA: 'CAN',
  CC: 'CCK',
  CD: 'COD',
  CF: 'CAF',
  CG: 'COG',
  CH: 'CHE',
  CI: 'CIV',
  CK: 'COK',
  CL: 'CHL',
  CM: 'CMR',
  CN: 'CHN',
  CO: 'COL',
  CR: 'CRI',
  CU: 'CUB',
  CV: 'CPV',
  CW: 'CUW',
  CX: 'CXR',
  CY: 'CYP',
  CZ: 'CZE',
  DE: 'DEU',
  DJ: 'DJI',
  DK: 'DNK',
  DM: 'DMA',
  DO: 'DOM',
  DZ: 'DZA',
  EC: 'ECU',
  EE: 'EST',
  EG: 'EGY',
  EH: 'ESH',
  ER: 'ERI',
  ES: 'ESP',
  ET: 'ETH',
  FI: 'FIN',
  FJ: 'FJI',
  FK: 'FLK',
  FM: 'FSM',
  FO: 'FRO',
  FR: 'FRA',
  GA: 'GAB',
  GB: 'GBR',
  GD: 'GRD',
  GE: 'GEO',
  GF: 'GUF',
  GG: 'GGY',
  GH: 'GHA',
  GI: 'GIB',
  GL: 'GRL',
  GM: 'GMB',
  GN: 'GIN',
  GP: 'GLP',
  GQ: 'GNQ',
  GR: 'GRC',
  GS: 'SGS',
  GT: 'GTM',
  GU: 'GUM',
  GW: 'GNB',
  GY: 'GUY',
  HK: 'HKG',
  HM: 'HMD',
  HN: 'HND',
  HR: 'HRV',
  HT: 'HTI',
  HU: 'HUN',
  ID: 'IDN',
  IE: 'IRL',
  IL: 'ISR',
  IM: 'IMN',
  IN: 'IND',
  IO: 'IOT',
  IQ: 'IRQ',
  IR: 'IRN',
  IS: 'ISL',
  IT: 'ITA',
  JE: 'JEY',
  JM: 'JAM',
  JO: 'JOR',
  JP: 'JPN',
  KE: 'KEN',
  KG: 'KGZ',
  KH: 'KHM',
  KI: 'KIR',
  KM: 'COM',
  KN: 'KNA',
  KP: 'PRK',
  KR: 'KOR',
  KW: 'KWT',
  KY: 'CYM',
  KZ: 'KAZ',
  LA: 'LAO',
  LB: 'LBN',
  LC: 'LCA',
  LI: 'LIE',
  LK: 'LKA',
  LR: 'LBR',
  LS: 'LSO',
  LT: 'LTU',
  LU: 'LUX',
  LV: 'LVA',
  LY: 'LBY',
  MA: 'MAR',
  MC: 'MCO',
  MD: 'MDA',
  ME: 'MNE',
  MF: 'MAF',
  MG: 'MDG',
  MH: 'MHL',
  MK: 'MKD',
  ML: 'MLI',
  MM: 'MMR',
  MN: 'MNG',
  MO: 'MAC',
  MP: 'MNP',
  MQ: 'MTQ',
  MR: 'MRT',
  MS: 'MSR',
  MT: 'MLT',
  MU: 'MUS',
  MV: 'MDV',
  MW: 'MWI',
  MX: 'MEX',
  MY: 'MYS',
  MZ: 'MOZ',
  NA: 'NAM',
  NC: 'NCL',
  NE: 'NER',
  NF: 'NFK',
  NG: 'NGA',
  NI: 'NIC',
  NL: 'NLD',
  NO: 'NOR',
  NP: 'NPL',
  NR: 'NRU',
  NU: 'NIU',
  NZ: 'NZL',
  OM: 'OMN',
  PA: 'PAN',
  PE: 'PER',
  PF: 'PYF',
  PG: 'PNG',
  PH: 'PHL',
  PK: 'PAK',
  PL: 'POL',
  PM: 'SPM',
  PN: 'PCN',
  PR: 'PRI',
  PS: 'PSE',
  PT: 'PRT',
  PW: 'PLW',
  PY: 'PRY',
  QA: 'QAT',
  RE: 'REU',
  RO: 'ROU',
  RS: 'SRB',
  RU: 'RUS',
  RW: 'RWA',
  SA: 'SAU',
  SB: 'SLB',
  SC: 'SYC',
  SD: 'SDN',
  SE: 'SWE',
  SG: 'SGP',
  SH: 'SHN',
  SI: 'SVN',
  SJ: 'SJM',
  SK: 'SVK',
  SL: 'SLE',
  SM: 'SMR',
  SN: 'SEN',
  SO: 'SOM',
  SR: 'SUR',
  SS: 'SSD',
  ST: 'STP',
  SV: 'SLV',
  SX: 'SXM',
  SY: 'SYR',
  SZ: 'SWZ',
  TC: 'TCA',
  TD: 'TCD',
  TF: 'ATF',
  TG: 'TGO',
  TH: 'THA',
  TJ: 'TJK',
  TK: 'TKL',
  TL: 'TLS',
  TM: 'TKM',
  TN: 'TUN',
  TO: 'TON',
  TR: 'TUR',
  TT: 'TTO',
  TV: 'TUV',
  TW: 'TWN',
  TZ: 'TZA',
  UA: 'UKR',
  UG: 'UGA',
  UM: 'UMI',
  US: 'USA',
  UY: 'URY',
  UZ: 'UZB',
  VA: 'VAT',
  VC: 'VCT',
  VE: 'VEN',
  VG: 'VGB',
  VI: 'VIR',
  VN: 'VNM',
  VU: 'VUT',
  WF: 'WLF',
  WS: 'WSM',
  YE: 'YEM',
  YT: 'MYT',
  ZA: 'ZAF',
  ZM: 'ZMB',
  ZW: 'ZWE',
};

export const ALPHA3_TO_ALPHA2: Readonly<Record<string, string>> =
  Object.fromEntries(
    Object.entries(ALPHA2_TO_ALPHA3).map(([a2, a3]) => [a3, a2]),
  );

/** Subdivisiones por país (alpha-3) → nombre, tal como las ofrece el formulario. */
export const COUNTRY_SUBDIVISION_NAMES: Readonly<
  Record<string, Readonly<Record<string, string>>>
> = {
  BOL: {
    B: 'El Beni',
    C: 'Cochabamba',
    H: 'Chuquisaca',
    L: 'La Paz',
    N: 'Pando',
    O: 'Oruro',
    P: 'Potosí',
    S: 'Santa Cruz',
    T: 'Tarija',
  },
  ARG: {
    C: 'Ciudad Autónoma de Buenos Aires',
    B: 'Buenos Aires',
    K: 'Catamarca',
    H: 'Chaco',
    U: 'Chubut',
    X: 'Córdoba',
    W: 'Corrientes',
    E: 'Entre Ríos',
    P: 'Formosa',
    Y: 'Jujuy',
    L: 'La Pampa',
    F: 'La Rioja',
    M: 'Mendoza',
    N: 'Misiones',
    Q: 'Neuquén',
    R: 'Río Negro',
    A: 'Salta',
    J: 'San Juan',
    D: 'San Luis',
    Z: 'Santa Cruz',
    S: 'Santa Fe',
    G: 'Santiago del Estero',
    V: 'Tierra del Fuego',
    T: 'Tucumán',
  },
  BRA: {
    AC: 'Acre',
    AL: 'Alagoas',
    AP: 'Amapá',
    AM: 'Amazonas',
    BA: 'Bahia',
    CE: 'Ceará',
    DF: 'Distrito Federal',
    ES: 'Espírito Santo',
    GO: 'Goiás',
    MA: 'Maranhão',
    MT: 'Mato Grosso',
    MS: 'Mato Grosso do Sul',
    MG: 'Minas Gerais',
    PA: 'Pará',
    PB: 'Paraíba',
    PR: 'Paraná',
    PE: 'Pernambuco',
    PI: 'Piauí',
    RJ: 'Rio de Janeiro',
    RN: 'Rio Grande do Norte',
    RS: 'Rio Grande do Sul',
    RO: 'Rondônia',
    RR: 'Roraima',
    SC: 'Santa Catarina',
    SP: 'São Paulo',
    SE: 'Sergipe',
    TO: 'Tocantins',
  },
  CHL: {
    AI: 'Aysén',
    AN: 'Antofagasta',
    AP: 'Arica y Parinacota',
    AR: 'La Araucanía',
    AT: 'Atacama',
    BI: 'Biobío',
    CO: 'Coquimbo',
    LI: 'Libertador Gral. Bernardo O\\',
    LL: 'Los Lagos',
    LR: 'Los Ríos',
    MA: 'Magallanes',
    ML: 'Maule',
    NB: 'Ñuble',
    RM: 'Región Metropolitana',
    TA: 'Tarapacá',
    VS: 'Valparaíso',
  },
  COL: {
    AMA: 'Amazonas',
    ANT: 'Antioquia',
    ARA: 'Arauca',
    ATL: 'Atlántico',
    BOL: 'Bolívar',
    BOY: 'Boyacá',
    CAL: 'Caldas',
    CAQ: 'Caquetá',
    CAS: 'Casanare',
    CAU: 'Cauca',
    CES: 'Cesar',
    CHO: 'Chocó',
    COR: 'Córdoba',
    CUN: 'Cundinamarca',
    DC: 'Bogotá D.C.',
    GUA: 'Guainía',
    GUV: 'Guaviare',
    HUI: 'Huila',
    LAG: 'La Guajira',
    MAG: 'Magdalena',
    MET: 'Meta',
    NAR: 'Nariño',
    NSA: 'Norte de Santander',
    PUT: 'Putumayo',
    QUI: 'Quindío',
    RIS: 'Risaralda',
    SAN: 'Santander',
    SAP: 'San Andrés y Providencia',
    SUC: 'Sucre',
    TOL: 'Tolima',
    VAC: 'Valle del Cauca',
    VID: 'Vichada',
  },
  CRI: {
    A: 'Alajuela',
    C: 'Cartago',
    G: 'Guanacaste',
    H: 'Heredia',
    L: 'Limón',
    P: 'Puntarenas',
    SJ: 'San José',
  },
  DOM: {
    '01': 'Distrito Nacional',
    '02': 'Azua',
    '03': 'Bahoruco',
    '04': 'Barahona',
    '05': 'Dajabón',
    '06': 'Duarte',
    '07': 'Elías Piña',
    '08': 'El Seibo',
    '09': 'Espaillat',
    '10': 'Independencia',
    '11': 'La Altagracia',
    '12': 'La Romana',
    '13': 'La Vega',
    '14': 'María Trinidad Sánchez',
    '15': 'Monte Cristi',
    '16': 'Pedernales',
    '17': 'Peravia',
    '18': 'Puerto Plata',
    '19': 'Hermanas Mirabal',
    '20': 'Samaná',
    '21': 'San Cristóbal',
    '22': 'San Juan',
    '23': 'San Pedro de Macorís',
    '24': 'Sánchez Ramírez',
    '25': 'Santiago',
    '26': 'Santiago Rodríguez',
    '27': 'Valverde',
    '28': 'Monseñor Nouel',
    '29': 'Monte Plata',
    '30': 'Hato Mayor',
    '31': 'San José de Ocoa',
    '32': 'Santo Domingo',
  },
  ECU: {
    A: 'Azuay',
    B: 'Bolívar',
    F: 'Cañar',
    C: 'Carchi',
    S: 'Chimborazo',
    X: 'Cotopaxi',
    H: 'El Oro',
    E: 'Esmeraldas',
    W: 'Galápagos',
    G: 'Guayas',
    I: 'Imbabura',
    L: 'Loja',
    R: 'Los Ríos',
    M: 'Manabí',
    SE: 'Morona Santiago',
    Z: 'Napo',
    D: 'Orellana',
    Y: 'Pastaza',
    P: 'Pichincha',
    SD: 'Santa Elena',
    U: 'Santo Domingo de los Tsáchilas',
    N: 'Sucumbíos',
    T: 'Tungurahua',
    O: 'Zamora Chinchipe',
  },
  SLV: {
    AH: 'Ahuachapán',
    CA: 'Cabañas',
    CH: 'Chalatenango',
    CU: 'Cuscatlán',
    LI: 'La Libertad',
    PA: 'La Paz',
    UN: 'La Unión',
    MO: 'Morazán',
    SM: 'San Miguel',
    SS: 'San Salvador',
    SA: 'Santa Ana',
    SV: 'San Vicente',
    SO: 'Sonsonate',
    US: 'Usulután',
  },
  GTM: {
    AV: 'Alta Verapaz',
    BV: 'Baja Verapaz',
    CM: 'Chimaltenango',
    CQ: 'Chiquimula',
    PE: 'El Petén',
    PR: 'El Progreso',
    QC: 'El Quiché',
    ES: 'Escuintla',
    GU: 'Guatemala',
    HU: 'Huehuetenango',
    IZ: 'Izabal',
    JA: 'Jalapa',
    JU: 'Jutiapa',
    QZ: 'Quetzaltenango',
    RE: 'Retalhuleu',
    SA: 'Sacatepéquez',
    SM: 'San Marcos',
    SO: 'Santa Rosa',
    SR: 'Sololá',
    SU: 'Suchitepéquez',
    TO: 'Totonicapán',
    ZA: 'Zacapa',
  },
  GUY: {
    BA: 'Barima-Waini',
    CU: 'Cuyuni-Mazaruni',
    DE: 'Demerara-Mahaica',
    EB: 'East Berbice-Corentyne',
    ES: 'Essequibo Islands-West Demerara',
    MA: 'Mahaica-Berbice',
    PM: 'Pomeroon-Supenaam',
    PT: 'Potaro-Siparuni',
    UD: 'Upper Demerara-Berbice',
    UT: 'Upper Takutu-Upper Essequibo',
  },
  HND: {
    AT: 'Atlántida',
    CH: 'Choluteca',
    CL: 'Colón',
    CM: 'Comayagua',
    CP: 'Copán',
    CR: 'Cortés',
    EP: 'El Paraíso',
    FM: 'Francisco Morazán',
    GD: 'Gracias a Dios',
    IN: 'Intibucá',
    IB: 'Islas de la Bahía',
    LP: 'La Paz',
    LE: 'Lempira',
    OC: 'Ocotepeque',
    OL: 'Olancho',
    SB: 'Santa Bárbara',
    VA: 'Valle',
    YO: 'Yoro',
  },
  MEX: {
    AGU: 'Aguascalientes',
    BCN: 'Baja California',
    BCS: 'Baja California Sur',
    CAM: 'Campeche',
    CHP: 'Chiapas',
    CHH: 'Chihuahua',
    CMX: 'Ciudad de México',
    COA: 'Coahuila',
    COL: 'Colima',
    DUR: 'Durango',
    GUA: 'Guanajuato',
    GRO: 'Guerrero',
    HID: 'Hidalgo',
    JAL: 'Jalisco',
    MEX: 'Estado de México',
    MIC: 'Michoacán',
    MOR: 'Morelos',
    NAY: 'Nayarit',
    NLE: 'Nuevo León',
    OAX: 'Oaxaca',
    PUE: 'Puebla',
    QUE: 'Querétaro',
    ROO: 'Quintana Roo',
    SLP: 'San Luis Potosí',
    SIN: 'Sinaloa',
    SON: 'Sonora',
    TAB: 'Tabasco',
    TAM: 'Tamaulipas',
    TLA: 'Tlaxcala',
    VER: 'Veracruz',
    YUC: 'Yucatán',
    ZAC: 'Zacatecas',
  },
  PAN: {
    '1': 'Bocas del Toro',
    '4': 'Chiriquí',
    '2': 'Coclé',
    '3': 'Colón',
    '5': 'Darién',
    '6': 'Herrera',
    '7': 'Los Santos',
    '8': 'Panamá',
    '10': 'Panamá Oeste',
    '9': 'Veraguas',
    EM: 'Emberá',
    KY: 'Guna Yala',
    NB: 'Ngäbe-Buglé',
  },
  PRY: {
    ASU: 'Asunción',
    '10': 'Alto Paraná',
    '16': 'Alto Paraguay',
    '13': 'Amambay',
    '17': 'Boquerón',
    '5': 'Caaguazú',
    '6': 'Caazapá',
    '14': 'Canindeyú',
    '11': 'Central',
    '1': 'Concepción',
    '3': 'Cordillera',
    '4': 'Guairá',
    '7': 'Itapúa',
    '8': 'Misiones',
    '12': 'Ñeembucú',
    '9': 'Paraguarí',
    '15': 'Presidente Hayes',
    '2': 'San Pedro',
  },
  PER: {
    AMA: 'Amazonas',
    ANC: 'Áncash',
    APU: 'Apurímac',
    ARE: 'Arequipa',
    AYA: 'Ayacucho',
    CAJ: 'Cajamarca',
    CAL: 'El Callao',
    CUS: 'Cusco',
    HUV: 'Huancavelica',
    HUC: 'Huánuco',
    ICA: 'Ica',
    JUN: 'Junín',
    LAL: 'La Libertad',
    LAM: 'Lambayeque',
    LIM: 'Lima',
    LOR: 'Loreto',
    MDD: 'Madre de Dios',
    MOQ: 'Moquegua',
    PAS: 'Pasco',
    PIU: 'Piura',
    PUN: 'Puno',
    SAM: 'San Martín',
    TAC: 'Tacna',
    TUM: 'Tumbes',
    UCA: 'Ucayali',
  },
  SUR: {
    BR: 'Brokopondo',
    CM: 'Commewijne',
    CR: 'Coronie',
    MA: 'Marowijne',
    NI: 'Nickerie',
    PR: 'Para',
    PM: 'Paramaribo',
    SA: 'Saramacca',
    SI: 'Sipaliwini',
    WA: 'Wanica',
  },
  URY: {
    AR: 'Artigas',
    CA: 'Canelones',
    CL: 'Cerro Largo',
    CO: 'Colonia',
    DU: 'Durazno',
    FS: 'Flores',
    FD: 'Florida',
    LA: 'Lavalleja',
    MA: 'Maldonado',
    MO: 'Montevideo',
    PA: 'Paysandú',
    RN: 'Río Negro',
    RV: 'Rivera',
    RO: 'Rocha',
    SA: 'Salto',
    SJ: 'San José',
    SO: 'Soriano',
    TA: 'Tacuarembó',
    TT: 'Treinta y Tres',
  },
  USA: {
    AL: 'Alabama',
    AK: 'Alaska',
    AZ: 'Arizona',
    AR: 'Arkansas',
    CA: 'California',
    CO: 'Colorado',
    CT: 'Connecticut',
    DE: 'Delaware',
    DC: 'District of Columbia',
    FL: 'Florida',
    GA: 'Georgia',
    HI: 'Hawaii',
    ID: 'Idaho',
    IL: 'Illinois',
    IN: 'Indiana',
    IA: 'Iowa',
    KS: 'Kansas',
    KY: 'Kentucky',
    LA: 'Louisiana',
    ME: 'Maine',
    MD: 'Maryland',
    MA: 'Massachusetts',
    MI: 'Michigan',
    MN: 'Minnesota',
    MS: 'Mississippi',
    MO: 'Missouri',
    MT: 'Montana',
    NE: 'Nebraska',
    NV: 'Nevada',
    NH: 'New Hampshire',
    NJ: 'New Jersey',
    NM: 'New Mexico',
    NC: 'North Carolina',
    ND: 'North Dakota',
    OH: 'Ohio',
    OK: 'Oklahoma',
    OR: 'Oregon',
    PA: 'Pennsylvania',
    RI: 'Rhode Island',
    SC: 'South Carolina',
    SD: 'South Dakota',
    TN: 'Tennessee',
    TX: 'Texas',
    UT: 'Utah',
    VT: 'Vermont',
    VA: 'Virginia',
    WA: 'Washington',
    WV: 'West Virginia',
    WI: 'Wisconsin',
    WY: 'Wyoming',
  },
};

/** Alpha-3 (o alpha-2) → alpha-2. Devuelve null si el código no se reconoce. */
export function toAlpha2(code: string | null | undefined): string | null {
  if (!code) return null;
  const upper = code.trim().toUpperCase();
  if (upper.length === 2) return ALPHA2_TO_ALPHA3[upper] ? upper : null;
  return ALPHA3_TO_ALPHA2[upper] ?? null;
}

/** Nombre de la subdivisión ("L" de BOL → "La Paz"). Si no hay catálogo, devuelve el valor tal cual. */
export function subdivisionName(
  countryAlpha3: string | null | undefined,
  code: string | null | undefined,
): string | undefined {
  if (!code) return undefined;
  const byCountry = countryAlpha3
    ? COUNTRY_SUBDIVISION_NAMES[countryAlpha3.toUpperCase()]
    : undefined;
  return byCountry?.[code] ?? code;
}
