-- KYB: datos que Tazapay exige además de lo que ya se pide para Bridge.
--
--   business_directors.is_director  respuesta a "¿Es director o miembro del
--        directorio?" del representante legal. Hasta ahora el backend enviaba
--        is_director=true fijo a Bridge (dato posiblemente falso para un
--        apoderado). business_ubos.is_director ya existía.
--   documents.document_subtype  tipo del comprobante de domicilio
--        (utility_bill / bank_statement / lease_agreement), las tres opciones
--        de "Select address proof" de Tazapay.
--   businesses.tazapay_vertical*  vertical de Tazapay propuesto con la tabla
--        NAICS → vertical y confirmado por el staff antes de enviar.
--   businesses.ownership_in_incorporation_doc  el cliente indica que el
--        testimonio de constitución (incorporation_certificate) ya muestra a los
--        socios y sus porcentajes vigentes: ese archivo se envía también como
--        estructura accionaria (Bridge ownership_information / Tazapay
--        shareholder_registry) sin subir otro.
--   businesses.shareholding_same_as_registration  casilla "Same as Business
--        Registration" de Tazapay. Solo la marca el staff (en unipersonales el
--        backend la calcula al enviar).
--   tazapay_industry_verticals / naics_tazapay_vertical_map  catálogo de los
--        295 verticales y equivalencias NAICS → vertical (gana el prefijo más
--        largo). Generado con Docuemntacion_nueva_integracion/scripts_tabla_naics.
--        Política: solo verticales que describen honestamente la actividad; sin
--        vertical o no elegible → la empresa queda solo con Bridge.

ALTER TABLE public.business_directors
  ADD COLUMN IF NOT EXISTS is_director boolean;

ALTER TABLE public.documents
  ADD COLUMN IF NOT EXISTS document_subtype text
  CHECK (document_subtype IS NULL OR document_subtype IN ('utility_bill', 'bank_statement', 'lease_agreement'));

CREATE TABLE IF NOT EXISTS public.tazapay_industry_verticals (
  vertical   text PRIMARY KEY,
  vgroup     text NOT NULL,
  high_risk  boolean NOT NULL DEFAULT false,
  is_active  boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.naics_tazapay_vertical_map (
  naics_prefix        text PRIMARY KEY CHECK (naics_prefix ~ '^[0-9]{2,6}$'),
  vertical            text REFERENCES public.tazapay_industry_verticals(vertical),
  quality             text NOT NULL
                      CHECK (quality IN ('exacta', 'generica', 'confirmar_tazapay', 'sin_vertical', 'no_elegible')),
  requires_compliance boolean NOT NULL DEFAULT false,
  note                text,
  CHECK ((quality IN ('sin_vertical', 'no_elegible')) = (vertical IS NULL))
);

ALTER TABLE public.businesses
  ADD COLUMN IF NOT EXISTS tazapay_vertical text REFERENCES public.tazapay_industry_verticals(vertical),
  ADD COLUMN IF NOT EXISTS tazapay_vertical_quality text,
  ADD COLUMN IF NOT EXISTS tazapay_vertical_confirmed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS tazapay_vertical_confirmed_at timestamptz,
  ADD COLUMN IF NOT EXISTS shareholding_same_as_registration boolean,
  ADD COLUMN IF NOT EXISTS ownership_in_incorporation_doc boolean;

ALTER TABLE public.tazapay_industry_verticals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.naics_tazapay_vertical_map ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.tazapay_industry_verticals FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.naics_tazapay_vertical_map FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.tazapay_industry_verticals TO service_role;
GRANT ALL ON TABLE public.naics_tazapay_vertical_map TO service_role;

INSERT INTO public.tazapay_industry_verticals (vertical, vgroup, high_risk) VALUES
  ('Digital Products - Apps, eBooks, Blogs & Games', 'Digital Products', false),
  ('Digital Products - Digital Merchandise', 'Digital Products', false),
  ('Digital Products - Music, Video, Channels & Podcast', 'Digital Products', false),
  ('Digital Products - Online Gaming (based on skill)', 'Digital Products', true),
  ('Digital Products - Other Digital Goods', 'Digital Products', false),
  ('Digital Products - Large Digital Goods Merchant (>25 Mn Txns annually)', 'Digital Products', false),
  ('Ecommerce - Home interior fixtures and decorating items', 'Ecommerce', false),
  ('Ecommerce - Miscellaneous Clothing (e.g., Swimwear)', 'Ecommerce', false),
  ('Ecommerce - Men and boys clothing', 'Ecommerce', false),
  ('Ecommerce - Meat & Poultry', 'Ecommerce', false),
  ('Ecommerce - Luggage and storage (incl backpacks, briefcases, purses and wallets)', 'Ecommerce', false),
  ('Ecommerce - Home, Decor & Furniture - Warehouse Stores', 'Ecommerce', false),
  ('Ecommerce - Home Appliances', 'Ecommerce', false),
  ('Ecommerce - Hobby, Toy, and Game Shops', 'Ecommerce', false),
  ('Ecommerce - Hardware stores', 'Ecommerce', false),
  ('Ecommerce - Electrical and plumbing supplies, tools and power tools', 'Ecommerce', false),
  ('Ecommerce - Glassware/Crystal Stores', 'Ecommerce', false),
  ('Ecommerce - Gift, Card, Novelty and Souvenir Shops', 'Ecommerce', false),
  ('Ecommerce - General Merchandise', 'Ecommerce', false),
  ('Ecommerce - General clothing stores (for men, women, children)', 'Ecommerce', false),
  ('Ecommerce - General clothing stores (for men and women)', 'Ecommerce', false),
  ('Ecommerce - Finished Furniture and accessories', 'Ecommerce', false),
  ('Ecommerce - Custom made clothing (to - order)', 'Ecommerce', false),
  ('Ecommerce - Fur jackets, coats', 'Ecommerce', false),
  ('Ecommerce - Food & Non - Alcohol Drinks (Miscellaneous / Specialty stores)', 'Ecommerce', false),
  ('Ecommerce - Food & Non - Alcohol Drinks (Grocery and Supermarkets)', 'Ecommerce', false),
  ('Ecommerce - Food & Non - Alcohol Drinks (Dairy products)', 'Ecommerce', false),
  ('Ecommerce - Food & Non - Alcohol Drinks (Confectionery / Candy)', 'Ecommerce', false),
  ('Ecommerce - Food & Non - Alcohol Drinks (Bakeries)', 'Ecommerce', false),
  ('Ecommerce - Equipment, Tool, Furniture, and Appliance Rental and Leasing', 'Ecommerce', false),
  ('Ecommerce - Electronic Hardware, Tools & Parts', 'Ecommerce', false),
  ('Ecommerce - Duty Free Stores', 'Ecommerce', false),
  ('Ecommerce - Dropshipping', 'Ecommerce', false),
  ('Ecommerce - Drapery, Window Covering, and Upholstery Stores', 'Ecommerce', false),
  ('Ecommerce - Diversified/Others', 'Ecommerce', false),
  ('Ecommerce - Discount Stores', 'Ecommerce', false),
  ('Ecommerce - Consumer Electronics (Mobiles)', 'Ecommerce', false),
  ('Ecommerce - Consumer Electronics', 'Ecommerce', false),
  ('Ecommerce - Clothing rental', 'Ecommerce', false),
  ('Ecommerce - Children clothing', 'Ecommerce', false),
  ('Ecommerce - Camera and Photographic Supply Stores', 'Ecommerce', false),
  ('Ecommerce - Building & Construction Materials (Glass, Paint and Wallpaper)', 'Ecommerce', false),
  ('Ecommerce - Building & Construction Materials (General)', 'Ecommerce', false),
  ('Ecommerce - Building & Construction Materials (Floor Covering)', 'Ecommerce', false),
  ('Ecommerce - Beauty Products & Cosmetics', 'Ecommerce', false),
  ('Ecommerce - Automobiles (B2B) - Motor Vehicle Supplies and New Parts', 'Ecommerce', false),
  ('Ecommerce - Automobiles - Motorcycle Shops and Dealers', 'Ecommerce', false),
  ('Ecommerce - Automobiles - Car and Truck Dealers (Used Only) Sales, Service, Repairs, Parts, and Leasing', 'Ecommerce', false),
  ('Ecommerce - Automobiles - Automobile sale/lease and repair, replacement of parts', 'Ecommerce', false),
  ('Ecommerce - Automobiles - Bicycles, bicycle parts, accessories and repair', 'Ecommerce', false),
  ('Ecommerce - Automobiles - Automobile tyre sale, installation and repair', 'Ecommerce', false),
  ('Ecommerce - Automobiles - Automobile parts/tools, accessories and equipment', 'Ecommerce', false),
  ('Ecommerce - Artwork / Art Dealers and Galleries', 'Ecommerce', false),
  ('Ecommerce - Art & Craft Materials, Handicraft and tools', 'Ecommerce', false),
  ('Ecommerce - Aroma, Organic & Herbal', 'Ecommerce', false),
  ('Ecommerce - AgriProducts - Garden Products and Fertilizers', 'Ecommerce', false),
  ('Ecommerce - AgriProducts - Florists and Novelty Products', 'Ecommerce', false),
  ('Ecommerce - Supplements or Nutraceuticals', 'Ecommerce', false),
  ('Ecommerce - Sports & Travel Goods', 'Ecommerce', false),
  ('Ecommerce - Sports clothing', 'Ecommerce', false),
  ('Ecommerce - Stamp and Coin Stores', 'Ecommerce', false),
  ('Ecommerce - Used Merchandise and Secondhand Stores', 'Ecommerce', false),
  ('Ecommerce - Sewing, Needlework, Fabric and Piece Goods Stores', 'Ecommerce', false),
  ('Ecommerce - Religious Goods Stores', 'Ecommerce', false),
  ('Ecommerce - Pet Food', 'Ecommerce', false),
  ('Ecommerce - Wigs, Toupees, hair pieces and extensions', 'Ecommerce', false),
  ('Ecommerce - Footwear including athletic footwear', 'Ecommerce', false),
  ('Ecommerce - Women fashion', 'Ecommerce', false),
  ('Ecommerce - Women accessories and specialty shops (e.g., handbags, scarfs, costume jewellery, etc)', 'Ecommerce', false),
  ('Ecommerce - Books Stores', 'Ecommerce', false),
  ('Ecommerce - Packaging, Office & Stationery', 'Ecommerce', false),
  ('Ecommerce - Music Stores - Musical Instruments, Pianos, and Sheet Music', 'Ecommerce', false),
  ('Ecommerce (B2B) - Building & Construction Materials (General)', 'Ecommerce (B2B)', false),
  ('Ecommerce (B2B) - Uniform supply and Commercial / Industrial clothing', 'Ecommerce (B2B)', false),
  ('Ecommerce (B2B) - Clocks, watches, silverware gems and jewelry, precious metals and jewelry repair', 'Ecommerce (B2B)', false),
  ('Ecommerce (B2B) - Commercial footwear', 'Ecommerce (B2B)', false),
  ('Ecommerce (B2B / Others) - Medical, dental, ophthalmic and hospital equipment and supplies & PPE', 'Ecommerce (B2B / Others)', false),
  ('Ecommerce (B2C) - Clocks, watches, silverware gems and jewelry, precious metals and jewelry repair', 'Ecommerce (B2C)', false),
  ('Education - Elementary and Secondary Schools', 'Education', false),
  ('Education - Elearning, Online Tutoring, Homework & Test Prep', 'Education', false),
  ('Education - Colleges, Universities, Professional Schools, and Junior Colleges', 'Education', false),
  ('Education - Online Education and Correspondence Schools', 'Education', false),
  ('Education - Colleges, School or Universities', 'Education', false),
  ('Education (others) - Other Educational Services not elsewhere classified', 'Education (others)', false),
  ('Education (others) - Business and Secretarial Schools', 'Education (others)', false),
  ('Education (others) - Vocational and Trade Schools', 'Education (others)', false),
  ('Financial Service - Life and Non - Life Insurance policies', 'Financial Service', true),
  ('Financial Service - Investment Banking & Financial Advisory', 'Financial Service', true),
  ('Financial Service - Other Financial Services (Automated Cash disbursements)', 'Financial Service', true),
  ('Financial Service - Other Financial Services (Manual Cash disbursements)', 'Financial Service', true),
  ('Financial Service - Other Financial Services (Non - classified)', 'Financial Service', true),
  ('Financial Service - Remittance & MSB', 'Financial Service', true),
  ('Financial Service - CFD and Forex', 'Financial Service', true),
  ('Financial Service - Banks and NBFI', 'Financial Service', true),
  ('Financial Service - Brokerages & Exchanges', 'Financial Service', true),
  ('Financial Service - Carbon Credit', 'Financial Service', true),
  ('Financial Service - Crowdfunding platform (equity)', 'Financial Service', true),
  ('Financial Service - Crowdfunding platforms (debt)', 'Financial Service', true),
  ('Financial Service - Digital Wallets, PSPs & Fintech', 'Financial Service', true),
  ('Financial Service - Fund, Wealth Management & Investment Holding', 'Financial Service', true),
  ('Financial Service - Prop Trading Simulation', 'Financial Service', true),
  ('Financial Services - Intra - Company Purchases', 'Financial Services', true),
  ('General Industries - Trade & Wholesale of General Goods', 'General Industries', false),
  ('General Industries - Trade & Wholesale of General Goods (Commercial Equipment (Not Elsewhere Classified))', 'General Industries', false),
  ('General Industries - Trade & Wholesale of General Goods (Chemicals and Allied Products (Not Elsewhere Classified))', 'General Industries', false),
  ('General Industries - Trade & Wholesale of General Goods (Computers Hardware, Software and Related equipment)', 'General Industries', false),
  ('General Industries - Trade & Wholesale of General Goods (Durable Goods (Not Elsewhere Classified))', 'General Industries', false),
  ('General Industries - Trade & Wholesale of General Goods (Flower)', 'General Industries', false),
  ('General Industries - Trade & Wholesale of General Goods (Hardware, Equipment and Supplies - bolts, nuts, screws, saws, nails, staples, hand tools, etc)', 'General Industries', false),
  ('General Industries - Trade & Wholesale of General Goods (Industrial Supplies (Not Elsewhere Classified))', 'General Industries', false),
  ('General Industries - Trade & Wholesale of General Goods (Semi - finished metal products - metal piping, tubing, nails, rods, etc)', 'General Industries', false),
  ('General Industries - Trade & Wholesale of General Goods (Non - durable goods - e.g., food products, ice, rubber, etc)', 'General Industries', false),
  ('General Industries - Trade & Wholesale of General Goods (Office and Commercial Furniture)', 'General Industries', false),
  ('General Industries - Trade & Wholesale of General Goods (Paints and related equipment)', 'General Industries', false),
  ('General Industries - Trade & Wholesale of General Goods (Photographic equipment, Photocopy machines, Microfilm, Typewriters, etc)', 'General Industries', false),
  ('General Industries - Trade & Wholesale of General Goods (Piece Goods, Notions, and Other Dry Goods)', 'General Industries', false),
  ('General Industries - Trade & Wholesale of General Goods (Commercial machines and equipment including food service and restaurant equipment)', 'General Industries', false),
  ('General Industries - Trade & Wholesale of General Goods (Stationery, Office Supplies, Printing and Writing Paper)', 'General Industries', false),
  ('General Industries - Trade & Wholesale of General Goods (Typewriter Stores - Sales, Rentals, and Service)', 'General Industries', false),
  ('General Industries - Agri, Forestry & Fishing', 'General Industries', false),
  ('General Industries - Trade & Wholesale of General Goods (Electrical Parts and equipment)', 'General Industries', false),
  ('General Service - Membership Organizations (Civic, Social, and Fraternal Associations)', 'General Service', false),
  ('General Service - Membership Organizations (e.g., Non - sports)', 'General Service', false),
  ('General Service - Membership Organizations (e.g., Professional Sports Clubs)', 'General Service', false),
  ('General Service - Membership Organizations (e.g., Recreation Sports Clubs)', 'General Service', false),
  ('General Service - Miscellaneous Personal Services (Not Elsewhere Classified)', 'General Service', false),
  ('General Service - Other General Services', 'General Service', false),
  ('General Service - Photography Studios', 'General Service', false),
  ('General Service - Recreation Services (Not Elsewhere Classified)', 'General Service', false),
  ('General Service - Recycling & Waste Management', 'General Service', false),
  ('General Service - Sporting and Recreational Camps', 'General Service', false),
  ('General Service - Utility', 'General Service', false),
  ('General Service - Computer Network/Information Services', 'General Service', false),
  ('General Service - Health and Beauty Spas', 'General Service', false),
  ('General Service - Membership Organizations (Automobile Associations)', 'General Service', false),
  ('General Services - Cleaning, Maintenance, and Janitorial Services', 'General Services', false),
  ('General Services - Exterminating and Disinfecting Services', 'General Services', false),
  ('General Services - Laundries - Family and Commercial', 'General Services', false),
  ('General Services - Laundry, Cleaning, and Garment Services', 'General Services', false),
  ('General Services - Testing Laboratories (Non - Medical Testing)', 'General Services', false),
  ('General Services - Dry Cleaners', 'General Services', false),
  ('General Services - Buying and Shopping Services and Clubs', 'General Services', false),
  ('General Services - Carpet and Upholstery Cleaning', 'General Services', false),
  ('Medical Services - Doctors, Physicians & Vets - Optometrists and Ophthalmologists', 'Medical Services', false),
  ('Medical Services - Doctors, Physicians & Vets - Chiropractors', 'Medical Services', false),
  ('Medical Services - Doctors, Physicians & Vets - Dentists and Orthodontists', 'Medical Services', false),
  ('Medical Services - Doctors, Physicians & Vets - Doctors and Physicians (Not Elsewhere Classified)', 'Medical Services', false),
  ('Medical Services - Doctors, Physicians & Vets - Opticians, Optical Goods, and Eyeglasses', 'Medical Services', false),
  ('Medical Services - Doctors, Physicians & Vets - Osteopaths', 'Medical Services', false),
  ('Medical Services - Doctors, Physicians & Vets - Podiatrists and Chiropodists', 'Medical Services', false),
  ('Medical Services - Doctors, Physicians & Vets - Veterinary Services', 'Medical Services', false),
  ('Medical Services - Hospitals', 'Medical Services', false),
  ('Medical Services - Medical and Dental Laboratories', 'Medical Services', false),
  ('Medical Services - Nursing and Personal Care Facilities', 'Medical Services', false),
  ('Medical Services - Telemedicine & Telehealth', 'Medical Services', false),
  ('Others - Camper, Recreational and Utility Trailer Dealers', 'Others', false),
  ('Others - Public Golf Courses', 'Others', false),
  ('Others - Parking Lots, Parking Meters and Garages', 'Others', false),
  ('Others - Package Tour Operators - Germany Only', 'Others', false),
  ('Others - Motor Homes Dealers', 'Others', false),
  ('Others - Motor Home and Recreational Vehicle Rentals', 'Others', false),
  ('Others - Motion Picture and Video Tape Production and Distribution', 'Others', false),
  ('Others - Mobile Home Dealers', 'Others', false),
  ('Others - Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers (Not Elsewhere Classified)', 'Others', false),
  ('Others - Information Retrieval Services', 'Others', false),
  ('Others - Fireplace, Fireplace Screens and Accessories Stores', 'Others', false),
  ('Others - Electric Vehicle Charging', 'Others', false),
  ('Others - Snowmobile Dealers', 'Others', false),
  ('Others - Computer Maintenance, Repair and Services (Not Elsewhere Classified)', 'Others', false),
  ('Others - Trailer Parks and Campgrounds', 'Others', false),
  ('Others - Automated Fuel Dispensers', 'Others', false),
  ('Others - Truck and Utility Trailer Rentals', 'Others', false),
  ('Others - Video Amusement Game Supplies', 'Others', false),
  ('Others - Public Warehousing and Storage - Farm Products, Refrigerated Goods, Household Goods, and Storage', 'Others', false),
  ('Others - Funding, Seed Capital Investment, and Venture Capital', 'Others', true),
  ('Others - Cryptocurrency', 'Others', true),
  ('Others - Books, Periodicals and Newspapers', 'Others', false),
  ('Others - Boat Dealers', 'Others', false),
  ('Others - Swimming Pools - Sales and Service', 'Others', false),
  ('Others - Telegraph Services', 'Others', false),
  ('Others - Tent and Awning Shops', 'Others', false),
  ('Others - Export, Import or Trading of Goods', 'Others', false),
  ('Others - Online: Advertising Services', 'Others', false),
  ('Other Offline - Offline: Car Washes', 'Other Offline', false),
  ('Other Offline - Offline: Bowling Alleys', 'Other Offline', false),
  ('Other Offline - Offline: Billiard and Pool Establishments', 'Other Offline', false),
  ('Other Offline - Offline: Beauty and Barber Shops', 'Other Offline', false),
  ('Other Offline - Offline: Bands, Orchestras, and Miscellaneous Entertainers (Not Elsewhere Classified)', 'Other Offline', false),
  ('Other Offline - Offline: Automotive Service Shops (Non - Dealer)', 'Other Offline', false),
  ('Other Offline - Offline: Automotive Paint Shops', 'Other Offline', false),
  ('Other Offline - Offline: Automotive Body Repair Shops', 'Other Offline', false),
  ('Other Offline - Offline: Air Conditioning and Refrigeration Repair Shops', 'Other Offline', false),
  ('Other Offline - Offline: Advertising Services', 'Other Offline', false),
  ('Other Offline - Offline: Wrecking and Salvage Yards', 'Other Offline', false),
  ('Other Offline - Offline: Wholesale Clubs', 'Other Offline', false),
  ('Other Offline - Offline: Welding Services', 'Other Offline', false),
  ('Other Offline - Offline: Watch, Clock and Jewelry Repair', 'Other Offline', false),
  ('Other Offline - Offline: Video Game Arcades/Establishments', 'Other Offline', false),
  ('Other Offline - Offline: Towing Services', 'Other Offline', false),
  ('Other Offline - Offline: Tolls and Bridge Fees', 'Other Offline', false),
  ('Other Offline - Offline: Tire Retreading and Repair Shops', 'Other Offline', false),
  ('Other Offline - Offline: Specialty Cleaning, Polishing and Sanitation Preparations', 'Other Offline', false),
  ('Other Offline - Offline: Special Trade Contractors (Not Elsewhere Classified)', 'Other Offline', false),
  ('Other Offline - Offline: Shoe Repair Shops, Shoe Shine Parlors, and Hat Cleaning Shops', 'Other Offline', false),
  ('Other Offline - Offline: Service Stations (With or without Ancillary Services)', 'Other Offline', false),
  ('Other Offline - Offline: Roofing, Siding, and Sheet Metal Work Contractors', 'Other Offline', false),
  ('Other Offline - Offline: Record Stores', 'Other Offline', false),
  ('Other Offline - Offline: News Dealers and Newsstands', 'Other Offline', false),
  ('Other Offline - Offline: Motion Picture Theaters', 'Other Offline', false),
  ('Other Offline - Offline: Miscellaneous Repair Shops and Related Services', 'Other Offline', false),
  ('Other Offline - Offline: Masonry, Stonework, Tile Setting, Plastering and Insulation Contractors', 'Other Offline', false),
  ('Other Offline - Offline: Heating, Plumbing, and Air Conditioning Contractors', 'Other Offline', false),
  ('Other Offline - Offline: Furniture - Reupholstery, Repair, and Refinishing', 'Other Offline', false),
  ('Other Offline - Offline: Funeral Services and Crematories', 'Other Offline', false),
  ('Other Offline - Offline: Fast Food Restaurants', 'Other Offline', false),
  ('Other Offline - Offline: Emergency Services (GCAS) (Visa use only)', 'Other Offline', false),
  ('Other Offline - Offline: Electronics Repair Shops', 'Other Offline', false),
  ('Other Offline - Offline: Electrical Contractors', 'Other Offline', false),
  ('Other Offline - Offline: Electrical and Small Appliance Repair Shops', 'Other Offline', false),
  ('Other Offline - Offline: Eating Places and Restaurants', 'Other Offline', false),
  ('Other Offline - Offline: DVD/Video Tape Rental Stores', 'Other Offline', false),
  ('Other Offline - Offline: Drinking Places (Alcoholic Beverages) - Bars, Taverns, Nightclubs, Cocktail Lounges, and Discotheques', 'Other Offline', false),
  ('Other Offline - Offline: Door To Door Sales', 'Other Offline', false),
  ('Other Offline - Offline: Dance Halls, Studios and Schools', 'Other Offline', false),
  ('Other Offline - Offline: Concrete Work Contractors', 'Other Offline', false),
  ('Other Offline - Offline: Caterers', 'Other Offline', false),
  ('Other Offline - Offline: Carpentry Contractors', 'Other Offline', false),
  ('Platforms - Other Platforms', 'Platforms', false),
  ('Platforms - Services Marketplace', 'Platforms', false),
  ('Platforms - Goods Marketplace', 'Platforms', false),
  ('Platforms - Goods Marketplace (with dedicated brand stores)', 'Platforms', false),
  ('Platforms - Digital Content Marketplace & Appstore', 'Platforms', false),
  ('Platforms - Super Apps', 'Platforms', false),
  ('Platforms - Social Media', 'Platforms', false),
  ('Professional Service - Credit Rating & Financial Data', 'Professional Service', false),
  ('Professional Service - App/Website/Software Development & Maintenance', 'Professional Service', false),
  ('Professional Service - BPO & KPO', 'Professional Service', false),
  ('Professional Service - Consulting & Coaching', 'Professional Service', false),
  ('Professional Service - Content Writing & Proof Reading', 'Professional Service', false),
  ('Professional Service - Counseling Services', 'Professional Service', false),
  ('Professional Service - Customer Survey & Market Research', 'Professional Service', false),
  ('Professional Service - Design & Architecture (Landscape and Horticultural Services)', 'Professional Service', false),
  ('Professional Service - Design & Architecture (Others)', 'Professional Service', false),
  ('Professional Service - Freelance (Graphic Design)', 'Professional Service', false),
  ('Professional Service - Freelance (Others)', 'Professional Service', false),
  ('Professional Service - Real Estate Sales & Brokerage', 'Professional Service', false),
  ('Professional Service - Printing, publishing and book binding (e.g., maps, newsletters, technical manuals)', 'Professional Service', false),
  ('Professional Service - Film development, photographic prints and enlargements', 'Professional Service', false),
  ('Professional Service - Photocopying, Reproduction, and Blueprinting Services', 'Professional Service', false),
  ('Professional Service - Typesetting, Plate Making and Related Services', 'Professional Service', false),
  ('Professional Services - Airports, Flying Fields, and Airport Terminals', 'Professional Services', false),
  ('Professional Services - Detective Agencies, Protective Services, and Security Services, including Armored Cars, and Guard Dogs', 'Professional Services', false),
  ('Professional Services - Employment Agencies and Temporary Help Services', 'Professional Services', false),
  ('Professional Services - Accounting, Auditing, Payroll, Bookkeeping Services', 'Professional Services', false),
  ('Professional Services - Architectural, Engineering, and Surveying Services', 'Professional Services', false),
  ('Professional Services - Legal Advices and Services', 'Professional Services', false),
  ('Professional Services - Tax Preparation Services', 'Professional Services', false),
  ('Professional Services - Motor Freight Carriers and Trucking - Local and Long Distance, Moving and Storage Companies, and Local Delivery Services', 'Professional Services', false),
  ('Professional Services - General Contractors - repair, remodeling, additions and alterations', 'Professional Services', false),
  ('Professional Services - Courier Services - Air and Ground, and Freight Forwarders', 'Professional Services', false),
  ('Professional Services (Govt) - Court Costs, Including Alimony and Child Support', 'Professional Services (Govt)', false),
  ('Professional Services (Govt) - Fines', 'Professional Services (Govt)', false),
  ('Professional Services (Govt) - Not elsewhere classified', 'Professional Services (Govt)', false),
  ('Professional Services (Govt) - Postal', 'Professional Services (Govt)', false),
  ('Professional Services (Govt) - Tax Payments', 'Professional Services (Govt)', false),
  ('Professional Services (Govt) - U.S. Federal Government Agencies or Departments', 'Professional Services (Govt)', false),
  ('Professional Services (Govt) - Bail and Bond Payments', 'Professional Services (Govt)', false),
  ('Software as a Service - Other Software as a Service', 'Software as a Service', false),
  ('Software as a Service - Employer on Record', 'Software as a Service', false),
  ('Software as a Service - Benefits, Rewards & Loyalty', 'Software as a Service', false),
  ('Software as a Service - Enterprise Software', 'Software as a Service', false),
  ('Software as a Service - Education Technology (EdTech)', 'Software as a Service', false),
  ('Telecommunication Services - Telecommunication Services, including Local and Long Distance Calls, Credit Card Calls, Calls Through Use of Magnetic - Stripe - Reading Telephones, and Fax Services', 'Telecommunication Services', false),
  ('Travel & Leisure - Other Travel & Leisure (Timeshares)', 'Travel & Leisure', false),
  ('Travel & Leisure - Other Transportation Services (Taxicabs and Limousines)', 'Travel & Leisure', false),
  ('Travel & Leisure - Other Transportation Services (Railroads)', 'Travel & Leisure', false),
  ('Travel & Leisure - Accommodation (Hotels, etc)', 'Travel & Leisure', false),
  ('Travel & Leisure - Airlines (Not Elsewhere Classified)', 'Travel & Leisure', false),
  ('Travel & Leisure - B2B Travel', 'Travel & Leisure', false),
  ('Travel & Leisure - Boat Rentals and Leasing', 'Travel & Leisure', false),
  ('Travel & Leisure - Destination Management Companies', 'Travel & Leisure', false),
  ('Travel & Leisure - Event Ticketing', 'Travel & Leisure', false),
  ('Travel & Leisure - Marinas, Marine Service, and Supplies', 'Travel & Leisure', false),
  ('Travel & Leisure - Other Transportation Services (Ambulance Services)', 'Travel & Leisure', false),
  ('Travel & Leisure - Travel Agencies & OTAs', 'Travel & Leisure', false),
  ('Travel & Leisure - Tourist Attractions (Tourist Attractions and Exhibits)', 'Travel & Leisure', false),
  ('Travel & Leisure - Tourist Attractions (Aquariums, Seaquariums, Dolphinariums, and Zoos)', 'Travel & Leisure', false),
  ('Travel & Leisure - Other Transportation Services (Automobile Rental Agency)', 'Travel & Leisure', false),
  ('Travel & Leisure - Other Transportation Services (Bus Lines)', 'Travel & Leisure', false),
  ('Travel & Leisure - Other Transportation Services (Local and Suburban Commuter Passenger Transportation, Including Ferries)', 'Travel & Leisure', false),
  ('Travel & Leisure - Other Transportation Services (Passenger Railways)', 'Travel & Leisure', false),
  ('Travel & Leisure - Tourist Attractions (Amusement Parks, Circuses, Carnivals, and Fortune Tellers)', 'Travel & Leisure', false),
  ('Travel & Leisure - Cruise Lines', 'Travel & Leisure', false),
  ('Travel & Leisure - Other Travel & Booking services (e.g., Visa)', 'Travel & Leisure', false),
  ('Travel & Leisure - Other Transportation Services (Transportation Services (Not Elsewhere Classified))', 'Travel & Leisure', false)
ON CONFLICT (vertical) DO UPDATE SET vgroup = EXCLUDED.vgroup, high_risk = EXCLUDED.high_risk;

INSERT INTO public.naics_tazapay_vertical_map (naics_prefix, vertical, quality, requires_compliance, note) VALUES
  ('11', 'General Industries - Agri, Forestry & Fishing', 'exacta', false, NULL),
  ('111910', 'General Industries - Agri, Forestry & Fishing', 'confirmar_tazapay', true, 'Cultivo de tabaco'),
  ('1142', NULL, 'sin_vertical', false, 'Caza y trampeo: Tazapay no la incluye en Agri, Forestry & Fishing'),
  ('21', NULL, 'sin_vertical', false, 'Tazapay no tiene vertical de extracción'),
  ('2122', NULL, 'sin_vertical', true, 'Incluye oro y plata (metales preciosos)'),
  ('2131', NULL, 'sin_vertical', false, 'Servicios de apoyo a la minería'),
  ('22', 'General Service - Utility', 'exacta', false, NULL),
  ('236', 'Professional Services - General Contractors - repair, remodeling, additions and alterations', 'exacta', false, NULL),
  ('237', NULL, 'sin_vertical', false, 'Obra civil pesada (ductos, líneas eléctricas, carreteras): no es "General Contractors - repair, remodeling"'),
  ('2372', NULL, 'sin_vertical', false, 'Loteo de terrenos: no es corretaje inmobiliario'),
  ('2381', 'Other Offline - Offline: Special Trade Contractors (Not Elsewhere Classified)', 'generica', false, NULL),
  ('23811', 'Other Offline - Offline: Concrete Work Contractors', 'exacta', false, NULL),
  ('23812', 'Other Offline - Offline: Special Trade Contractors (Not Elsewhere Classified)', 'generica', false, 'Contratistas de estructura de acero'),
  ('23813', 'Other Offline - Offline: Carpentry Contractors', 'exacta', false, NULL),
  ('23814', 'Other Offline - Offline: Masonry, Stonework, Tile Setting, Plastering and Insulation Contractors', 'exacta', false, NULL),
  ('23816', 'Other Offline - Offline: Roofing, Siding, and Sheet Metal Work Contractors', 'exacta', false, NULL),
  ('23817', 'Other Offline - Offline: Roofing, Siding, and Sheet Metal Work Contractors', 'exacta', false, NULL),
  ('2382', 'Other Offline - Offline: Special Trade Contractors (Not Elsewhere Classified)', 'generica', false, NULL),
  ('23821', 'Other Offline - Offline: Electrical Contractors', 'exacta', false, NULL),
  ('23822', 'Other Offline - Offline: Heating, Plumbing, and Air Conditioning Contractors', 'exacta', false, NULL),
  ('2383', 'Other Offline - Offline: Special Trade Contractors (Not Elsewhere Classified)', 'generica', false, NULL),
  ('23831', 'Other Offline - Offline: Masonry, Stonework, Tile Setting, Plastering and Insulation Contractors', 'exacta', false, NULL),
  ('23834', 'Other Offline - Offline: Masonry, Stonework, Tile Setting, Plastering and Insulation Contractors', 'exacta', false, NULL),
  ('23835', 'Other Offline - Offline: Carpentry Contractors', 'exacta', false, NULL),
  ('2389', 'Other Offline - Offline: Special Trade Contractors (Not Elsewhere Classified)', 'exacta', false, NULL),
  ('31', NULL, 'sin_vertical', false, NULL),
  ('311111', NULL, 'sin_vertical', false, NULL),
  ('3113', NULL, 'sin_vertical', false, NULL),
  ('3115', NULL, 'sin_vertical', false, NULL),
  ('3116', NULL, 'sin_vertical', false, NULL),
  ('311811', 'Ecommerce - Food & Non - Alcohol Drinks (Bakeries)', 'exacta', false, 'Panadería con venta al público'),
  ('31212', NULL, 'sin_vertical', true, 'Alcohol'),
  ('31213', NULL, 'sin_vertical', true, 'Alcohol'),
  ('31214', NULL, 'sin_vertical', true, 'Alcohol'),
  ('3122', NULL, 'no_elegible', true, 'Tabaco: sin vertical'),
  ('313', NULL, 'sin_vertical', false, NULL),
  ('314', NULL, 'sin_vertical', false, NULL),
  ('315', NULL, 'sin_vertical', false, NULL),
  ('316', NULL, 'sin_vertical', false, NULL),
  ('3162', NULL, 'sin_vertical', false, NULL),
  ('321', NULL, 'sin_vertical', false, NULL),
  ('322', NULL, 'sin_vertical', false, NULL),
  ('3222', NULL, 'sin_vertical', false, NULL),
  ('323', 'Professional Service - Printing, publishing and book binding (e.g., maps, newsletters, technical manuals)', 'exacta', false, 'Imprenta: es el servicio de impresión'),
  ('324', NULL, 'sin_vertical', false, NULL),
  ('325', NULL, 'sin_vertical', false, NULL),
  ('3254', NULL, 'sin_vertical', true, 'Farmacéutica'),
  ('32551', NULL, 'sin_vertical', false, NULL),
  ('32562', NULL, 'sin_vertical', false, NULL),
  ('325920', NULL, 'no_elegible', true, 'Explosivos'),
  ('326', NULL, 'sin_vertical', false, NULL),
  ('327', NULL, 'sin_vertical', false, NULL),
  ('327212', NULL, 'sin_vertical', false, NULL),
  ('327213', NULL, 'sin_vertical', false, NULL),
  ('331', NULL, 'sin_vertical', false, NULL),
  ('332', NULL, 'sin_vertical', false, NULL),
  ('3322', NULL, 'sin_vertical', false, NULL),
  ('3325', NULL, 'sin_vertical', false, NULL),
  ('33272', NULL, 'sin_vertical', false, NULL),
  ('332992', NULL, 'no_elegible', true, 'Munición'),
  ('332993', NULL, 'no_elegible', true, 'Munición'),
  ('332994', NULL, 'no_elegible', true, 'Armas'),
  ('333', NULL, 'sin_vertical', false, NULL),
  ('333241', NULL, 'sin_vertical', false, NULL),
  ('3333', NULL, 'sin_vertical', false, NULL),
  ('334', NULL, 'sin_vertical', false, NULL),
  ('3341', NULL, 'sin_vertical', false, NULL),
  ('3345', NULL, 'sin_vertical', false, NULL),
  ('3346', NULL, 'sin_vertical', false, NULL),
  ('335', NULL, 'sin_vertical', false, NULL),
  ('3352', NULL, 'sin_vertical', false, NULL),
  ('336', NULL, 'sin_vertical', false, NULL),
  ('3364', NULL, 'sin_vertical', false, NULL),
  ('336414', NULL, 'no_elegible', true, 'Misiles'),
  ('336415', NULL, 'no_elegible', true, 'Misiles'),
  ('336419', NULL, 'no_elegible', true, 'Misiles'),
  ('3365', NULL, 'sin_vertical', false, NULL),
  ('3366', NULL, 'sin_vertical', false, NULL),
  ('336991', NULL, 'sin_vertical', false, NULL),
  ('336992', NULL, 'no_elegible', true, 'Vehículos militares'),
  ('336999', NULL, 'sin_vertical', false, NULL),
  ('3371', NULL, 'sin_vertical', false, NULL),
  ('3372', NULL, 'sin_vertical', false, NULL),
  ('3379', NULL, 'sin_vertical', false, NULL),
  ('337920', NULL, 'sin_vertical', false, NULL),
  ('3391', NULL, 'sin_vertical', false, 'Fabricación de equipo médico: Tazapay solo tiene la venta B2B'),
  ('3399', NULL, 'sin_vertical', false, NULL),
  ('339910', NULL, 'sin_vertical', true, 'Joyería y metales preciosos'),
  ('339920', NULL, 'sin_vertical', false, NULL),
  ('339930', NULL, 'sin_vertical', false, NULL),
  ('339940', NULL, 'sin_vertical', false, NULL),
  ('42', 'General Industries - Trade & Wholesale of General Goods', 'generica', false, NULL),
  ('4231', 'Ecommerce - Automobiles (B2B) - Motor Vehicle Supplies and New Parts', 'exacta', false, NULL),
  ('423210', 'General Industries - Trade & Wholesale of General Goods (Office and Commercial Furniture)', 'generica', false, NULL),
  ('423220', 'General Industries - Trade & Wholesale of General Goods (Durable Goods (Not Elsewhere Classified))', 'generica', false, NULL),
  ('4233', 'Ecommerce (B2B) - Building & Construction Materials (General)', 'exacta', false, NULL),
  ('423410', 'General Industries - Trade & Wholesale of General Goods (Photographic equipment, Photocopy machines, Microfilm, Typewriters, etc)', 'exacta', false, NULL),
  ('423420', 'General Industries - Trade & Wholesale of General Goods (Commercial Equipment (Not Elsewhere Classified))', 'generica', false, NULL),
  ('423430', 'General Industries - Trade & Wholesale of General Goods (Computers Hardware, Software and Related equipment)', 'exacta', false, NULL),
  ('423440', 'General Industries - Trade & Wholesale of General Goods (Commercial machines and equipment including food service and restaurant equipment)', 'exacta', false, NULL),
  ('423450', 'Ecommerce (B2B / Others) - Medical, dental, ophthalmic and hospital equipment and supplies & PPE', 'exacta', false, NULL),
  ('423460', 'Ecommerce (B2B / Others) - Medical, dental, ophthalmic and hospital equipment and supplies & PPE', 'exacta', false, NULL),
  ('423490', 'General Industries - Trade & Wholesale of General Goods (Commercial Equipment (Not Elsewhere Classified))', 'generica', false, NULL),
  ('4235', 'General Industries - Trade & Wholesale of General Goods (Semi - finished metal products - metal piping, tubing, nails, rods, etc)', 'exacta', false, NULL),
  ('423520', 'General Industries - Trade & Wholesale of General Goods', 'confirmar_tazapay', true, 'Comercio de carbón y minerales'),
  ('4236', 'General Industries - Trade & Wholesale of General Goods (Electrical Parts and equipment)', 'exacta', false, NULL),
  ('423620', 'General Industries - Trade & Wholesale of General Goods (Durable Goods (Not Elsewhere Classified))', 'generica', false, NULL),
  ('4237', 'General Industries - Trade & Wholesale of General Goods (Hardware, Equipment and Supplies - bolts, nuts, screws, saws, nails, staples, hand tools, etc)', 'exacta', false, NULL),
  ('423740', 'General Industries - Trade & Wholesale of General Goods (Commercial machines and equipment including food service and restaurant equipment)', 'generica', false, NULL),
  ('4238', 'General Industries - Trade & Wholesale of General Goods (Commercial Equipment (Not Elsewhere Classified))', 'exacta', false, NULL),
  ('423820', 'General Industries - Trade & Wholesale of General Goods (Commercial Equipment (Not Elsewhere Classified))', 'generica', false, NULL),
  ('423850', 'General Industries - Trade & Wholesale of General Goods (Commercial machines and equipment including food service and restaurant equipment)', 'exacta', false, NULL),
  ('4239', 'General Industries - Trade & Wholesale of General Goods (Durable Goods (Not Elsewhere Classified))', 'generica', false, NULL),
  ('423930', 'General Service - Recycling & Waste Management', 'exacta', false, NULL),
  ('423940', 'Ecommerce (B2B) - Clocks, watches, silverware gems and jewelry, precious metals and jewelry repair', 'exacta', true, 'Metales y piedras preciosas'),
  ('4241', 'General Industries - Trade & Wholesale of General Goods (Stationery, Office Supplies, Printing and Writing Paper)', 'exacta', false, NULL),
  ('424130', 'General Industries - Trade & Wholesale of General Goods (Non - durable goods - e.g., food products, ice, rubber, etc)', 'generica', false, NULL),
  ('4242', 'General Industries - Trade & Wholesale of General Goods (Non - durable goods - e.g., food products, ice, rubber, etc)', 'confirmar_tazapay', true, 'Mayorista de medicamentos: producto regulado'),
  ('424310', 'General Industries - Trade & Wholesale of General Goods (Piece Goods, Notions, and Other Dry Goods)', 'exacta', false, NULL),
  ('424340', 'Ecommerce (B2B) - Commercial footwear', 'exacta', false, NULL),
  ('424350', 'General Industries - Trade & Wholesale of General Goods', 'generica', false, 'Mayorista de ropa'),
  ('4244', 'General Industries - Trade & Wholesale of General Goods (Non - durable goods - e.g., food products, ice, rubber, etc)', 'exacta', false, NULL),
  ('4245', 'General Industries - Trade & Wholesale of General Goods (Non - durable goods - e.g., food products, ice, rubber, etc)', 'generica', false, NULL),
  ('4246', 'General Industries - Trade & Wholesale of General Goods (Chemicals and Allied Products (Not Elsewhere Classified))', 'exacta', false, NULL),
  ('4247', 'General Industries - Trade & Wholesale of General Goods', 'confirmar_tazapay', true, 'Mayorista de combustibles'),
  ('4248', 'General Industries - Trade & Wholesale of General Goods (Non - durable goods - e.g., food products, ice, rubber, etc)', 'confirmar_tazapay', true, 'Mayorista de bebidas alcohólicas'),
  ('424910', 'General Industries - Trade & Wholesale of General Goods', 'generica', false, 'Mayorista de insumos agrícolas'),
  ('424920', 'Others - Books, Periodicals and Newspapers', 'generica', false, NULL),
  ('424930', 'General Industries - Trade & Wholesale of General Goods (Flower)', 'exacta', false, NULL),
  ('424940', NULL, 'no_elegible', true, 'Tabaco y cigarrillos electrónicos'),
  ('424950', 'General Industries - Trade & Wholesale of General Goods (Paints and related equipment)', 'exacta', false, NULL),
  ('424990', 'General Industries - Trade & Wholesale of General Goods (Non - durable goods - e.g., food products, ice, rubber, etc)', 'generica', false, NULL),
  ('4251', 'Others - Export, Import or Trading of Goods', 'exacta', false, NULL),
  ('44', 'Ecommerce - Diversified/Others', 'generica', false, NULL),
  ('441110', 'Ecommerce - Automobiles - Automobile sale/lease and repair, replacement of parts', 'exacta', false, NULL),
  ('441120', 'Ecommerce - Automobiles - Car and Truck Dealers (Used Only) Sales, Service, Repairs, Parts, and Leasing', 'exacta', false, NULL),
  ('441210', 'Others - Motor Homes Dealers', 'generica', false, NULL),
  ('441222', 'Others - Boat Dealers', 'exacta', false, NULL),
  ('441227', 'Ecommerce - Automobiles - Motorcycle Shops and Dealers', 'exacta', false, NULL),
  ('441330', 'Ecommerce - Automobiles - Automobile parts/tools, accessories and equipment', 'exacta', false, NULL),
  ('441340', 'Ecommerce - Automobiles - Automobile tyre sale, installation and repair', 'exacta', false, NULL),
  ('444110', 'Ecommerce - Building & Construction Materials (General)', 'generica', false, NULL),
  ('444120', 'Ecommerce - Building & Construction Materials (Glass, Paint and Wallpaper)', 'exacta', false, NULL),
  ('444140', 'Ecommerce - Hardware stores', 'exacta', false, NULL),
  ('444180', 'Ecommerce - Building & Construction Materials (General)', 'generica', false, NULL),
  ('444230', 'Ecommerce - AgriProducts - Garden Products and Fertilizers', 'generica', false, NULL),
  ('444240', 'Ecommerce - AgriProducts - Garden Products and Fertilizers', 'exacta', false, NULL),
  ('4451', 'Ecommerce - Food & Non - Alcohol Drinks (Grocery and Supermarkets)', 'exacta', false, NULL),
  ('445132', 'Ecommerce - General Merchandise', 'generica', false, 'Máquinas expendedoras'),
  ('4452', 'Ecommerce - Food & Non - Alcohol Drinks (Miscellaneous / Specialty stores)', 'exacta', false, NULL),
  ('445240', 'Ecommerce - Meat & Poultry', 'exacta', false, NULL),
  ('445291', 'Ecommerce - Food & Non - Alcohol Drinks (Bakeries)', 'exacta', false, NULL),
  ('445292', 'Ecommerce - Food & Non - Alcohol Drinks (Confectionery / Candy)', 'exacta', false, NULL),
  ('4453', NULL, 'sin_vertical', true, 'Licorería: el único vertical de bebidas es "Non - Alcohol Drinks"'),
  ('449110', 'Ecommerce - Finished Furniture and accessories', 'exacta', false, NULL),
  ('449121', 'Ecommerce - Building & Construction Materials (Floor Covering)', 'exacta', false, NULL),
  ('449122', 'Ecommerce - Drapery, Window Covering, and Upholstery Stores', 'exacta', false, NULL),
  ('449129', 'Ecommerce - Home interior fixtures and decorating items', 'exacta', false, NULL),
  ('4492', 'Ecommerce - Consumer Electronics', 'exacta', false, NULL),
  ('45', 'Ecommerce - Diversified/Others', 'generica', false, NULL),
  ('4541', 'Ecommerce - Diversified/Others', 'generica', false, 'Venta por catálogo o a distancia'),
  ('4543', 'Other Offline - Offline: Door To Door Sales', 'exacta', false, NULL),
  ('4551', 'Ecommerce - General Merchandise', 'exacta', false, NULL),
  ('455211', 'Other Offline - Offline: Wholesale Clubs', 'exacta', false, NULL),
  ('455219', 'Ecommerce - General Merchandise', 'exacta', false, NULL),
  ('456110', NULL, 'sin_vertical', true, 'Farmacia: sin vertical propio'),
  ('456120', 'Ecommerce - Beauty Products & Cosmetics', 'exacta', false, NULL),
  ('456130', 'Medical Services - Doctors, Physicians & Vets - Opticians, Optical Goods, and Eyeglasses', 'exacta', false, NULL),
  ('456191', 'Ecommerce - Supplements or Nutraceuticals', 'exacta', false, NULL),
  ('4571', 'Other Offline - Offline: Service Stations (With or without Ancillary Services)', 'exacta', false, NULL),
  ('4572', NULL, 'sin_vertical', false, 'Venta de combustible'),
  ('4581', 'Ecommerce - General clothing stores (for men, women, children)', 'exacta', false, NULL),
  ('4582', 'Ecommerce - Footwear including athletic footwear', 'exacta', false, NULL),
  ('458310', 'Ecommerce (B2C) - Clocks, watches, silverware gems and jewelry, precious metals and jewelry repair', 'exacta', true, 'Joyería'),
  ('458320', 'Ecommerce - Luggage and storage (incl backpacks, briefcases, purses and wallets)', 'exacta', false, NULL),
  ('459110', 'Ecommerce - Sports & Travel Goods', 'exacta', false, NULL),
  ('459120', 'Ecommerce - Hobby, Toy, and Game Shops', 'exacta', false, NULL),
  ('459130', 'Ecommerce - Sewing, Needlework, Fabric and Piece Goods Stores', 'exacta', false, NULL),
  ('459140', 'Ecommerce - Music Stores - Musical Instruments, Pianos, and Sheet Music', 'exacta', false, NULL),
  ('4592', 'Ecommerce - Books Stores', 'exacta', false, NULL),
  ('4593', 'Ecommerce - AgriProducts - Florists and Novelty Products', 'exacta', false, NULL),
  ('459410', 'Ecommerce - Packaging, Office & Stationery', 'exacta', false, NULL),
  ('459420', 'Ecommerce - Gift, Card, Novelty and Souvenir Shops', 'exacta', false, NULL),
  ('4595', 'Ecommerce - Used Merchandise and Secondhand Stores', 'exacta', false, NULL),
  ('459910', 'Ecommerce - Pet Food', 'generica', false, NULL),
  ('459920', 'Ecommerce - Artwork / Art Dealers and Galleries', 'exacta', false, NULL),
  ('459930', 'Others - Mobile Home Dealers', 'exacta', false, NULL),
  ('459991', NULL, 'no_elegible', true, 'Tabaco y cigarrillos electrónicos'),
  ('48', 'Travel & Leisure - Other Transportation Services (Transportation Services (Not Elsewhere Classified))', 'generica', false, NULL),
  ('481111', 'Travel & Leisure - Airlines (Not Elsewhere Classified)', 'exacta', false, NULL),
  ('481112', 'Professional Services - Courier Services - Air and Ground, and Freight Forwarders', 'exacta', false, NULL),
  ('481211', 'Travel & Leisure - Airlines (Not Elsewhere Classified)', 'generica', false, NULL),
  ('481212', 'Professional Services - Courier Services - Air and Ground, and Freight Forwarders', 'exacta', false, NULL),
  ('481219', 'Travel & Leisure - Other Transportation Services (Transportation Services (Not Elsewhere Classified))', 'generica', false, NULL),
  ('4821', 'Travel & Leisure - Other Transportation Services (Railroads)', 'exacta', false, NULL),
  ('483', 'Travel & Leisure - Other Transportation Services (Transportation Services (Not Elsewhere Classified))', 'generica', false, 'Transporte de carga marítimo o fluvial'),
  ('483112', 'Travel & Leisure - Cruise Lines', 'exacta', false, NULL),
  ('483114', 'Travel & Leisure - Other Transportation Services (Local and Suburban Commuter Passenger Transportation, Including Ferries)', 'exacta', false, NULL),
  ('483212', 'Travel & Leisure - Other Transportation Services (Local and Suburban Commuter Passenger Transportation, Including Ferries)', 'exacta', false, NULL),
  ('484', 'Professional Services - Motor Freight Carriers and Trucking - Local and Long Distance, Moving and Storage Companies, and Local Delivery Services', 'exacta', false, NULL),
  ('4851', 'Travel & Leisure - Other Transportation Services (Local and Suburban Commuter Passenger Transportation, Including Ferries)', 'exacta', false, NULL),
  ('4852', 'Travel & Leisure - Other Transportation Services (Bus Lines)', 'exacta', false, NULL),
  ('4853', 'Travel & Leisure - Other Transportation Services (Taxicabs and Limousines)', 'exacta', false, NULL),
  ('4854', 'Travel & Leisure - Other Transportation Services (Bus Lines)', 'generica', false, NULL),
  ('4855', 'Travel & Leisure - Other Transportation Services (Bus Lines)', 'generica', false, NULL),
  ('4859', 'Travel & Leisure - Other Transportation Services (Transportation Services (Not Elsewhere Classified))', 'exacta', false, NULL),
  ('486', NULL, 'sin_vertical', false, 'Oleoductos y gasoductos'),
  ('487', 'Travel & Leisure - Tourist Attractions (Tourist Attractions and Exhibits)', 'generica', false, NULL),
  ('4881', 'Professional Services - Airports, Flying Fields, and Airport Terminals', 'exacta', false, NULL),
  ('4882', 'Travel & Leisure - Other Transportation Services (Railroads)', 'generica', false, NULL),
  ('4883', 'Travel & Leisure - Other Transportation Services (Transportation Services (Not Elsewhere Classified))', 'generica', false, NULL),
  ('488410', 'Other Offline - Offline: Towing Services', 'exacta', false, NULL),
  ('4885', 'Professional Services - Courier Services - Air and Ground, and Freight Forwarders', 'exacta', false, NULL),
  ('4889', 'Travel & Leisure - Other Transportation Services (Transportation Services (Not Elsewhere Classified))', 'generica', false, 'Embalaje y otros servicios de transporte'),
  ('4911', 'Professional Services (Govt) - Postal', 'generica', false, NULL),
  ('4921', 'Professional Services - Courier Services - Air and Ground, and Freight Forwarders', 'exacta', false, NULL),
  ('4922', 'Professional Services - Motor Freight Carriers and Trucking - Local and Long Distance, Moving and Storage Companies, and Local Delivery Services', 'exacta', false, NULL),
  ('4931', 'Others - Public Warehousing and Storage - Farm Products, Refrigerated Goods, Household Goods, and Storage', 'exacta', false, NULL),
  ('5121', 'Others - Motion Picture and Video Tape Production and Distribution', 'exacta', false, NULL),
  ('51213', 'Other Offline - Offline: Motion Picture Theaters', 'exacta', false, NULL),
  ('5122', 'Digital Products - Music, Video, Channels & Podcast', 'generica', false, NULL),
  ('5131', 'Others - Books, Periodicals and Newspapers', 'generica', false, NULL),
  ('513140', 'Others - Information Retrieval Services', 'generica', false, NULL),
  ('513191', 'Ecommerce - Gift, Card, Novelty and Souvenir Shops', 'generica', false, NULL),
  ('513199', 'Professional Service - Printing, publishing and book binding (e.g., maps, newsletters, technical manuals)', 'generica', false, NULL),
  ('5132', 'Software as a Service - Other Software as a Service', 'exacta', false, NULL),
  ('5152', 'Digital Products - Music, Video, Channels & Podcast', 'generica', false, NULL),
  ('5161', 'Digital Products - Music, Video, Channels & Podcast', 'generica', false, NULL),
  ('5162', 'Platforms - Social Media', 'generica', false, NULL),
  ('517', 'Telecommunication Services - Telecommunication Services, including Local and Long Distance Calls, Credit Card Calls, Calls Through Use of Magnetic - Stripe - Reading Telephones, and Fax Services', 'exacta', false, NULL),
  ('5182', 'General Service - Computer Network/Information Services', 'exacta', false, NULL),
  ('5192', 'Others - Information Retrieval Services', 'exacta', false, NULL),
  ('52', 'Financial Service - Other Financial Services (Non - classified)', 'generica', true, NULL),
  ('521110', NULL, 'no_elegible', true, 'Banco central: no es cliente'),
  ('5221', 'Financial Service - Banks and NBFI', 'exacta', true, NULL),
  ('5222', 'Financial Service - Banks and NBFI', 'exacta', true, NULL),
  ('522310', 'Financial Service - Other Financial Services (Non - classified)', 'generica', true, 'Corredores de préstamos'),
  ('522320', 'Financial Service - Digital Wallets, PSPs & Fintech', 'exacta', true, 'Procesamiento de pagos (PSP)'),
  ('522390', 'Financial Service - Remittance & MSB', 'exacta', true, 'Incluye transmisión de dinero y cambio de cheques'),
  ('523150', 'Financial Service - Investment Banking & Financial Advisory', 'exacta', true, NULL),
  ('523160', 'Financial Service - Brokerages & Exchanges', 'confirmar_tazapay', true, 'Incluye compra-venta de divisas (casas de cambio): confirmar vertical'),
  ('5232', 'Financial Service - Brokerages & Exchanges', 'exacta', true, NULL),
  ('523910', 'Financial Service - Other Financial Services (Non - classified)', 'generica', true, NULL),
  ('523940', 'Financial Service - Fund, Wealth Management & Investment Holding', 'exacta', true, NULL),
  ('523991', 'Financial Service - Fund, Wealth Management & Investment Holding', 'generica', true, NULL),
  ('523999', 'Financial Service - Other Financial Services (Non - classified)', 'generica', true, NULL),
  ('524', 'Financial Service - Life and Non - Life Insurance policies', 'exacta', true, NULL),
  ('525', 'Financial Service - Fund, Wealth Management & Investment Holding', 'generica', true, NULL),
  ('531', 'Professional Service - Real Estate Sales & Brokerage', 'confirmar_tazapay', true, 'Arrendamiento de inmuebles propios: Tazapay solo tiene corretaje'),
  ('5312', 'Professional Service - Real Estate Sales & Brokerage', 'exacta', false, NULL),
  ('532111', 'Travel & Leisure - Other Transportation Services (Automobile Rental Agency)', 'exacta', false, NULL),
  ('532112', 'Travel & Leisure - Other Transportation Services (Automobile Rental Agency)', 'exacta', false, NULL),
  ('532120', 'Others - Truck and Utility Trailer Rentals', 'exacta', false, NULL),
  ('5322', 'Ecommerce - Equipment, Tool, Furniture, and Appliance Rental and Leasing', 'exacta', false, NULL),
  ('532281', 'Ecommerce - Clothing rental', 'exacta', false, NULL),
  ('532282', 'Other Offline - Offline: DVD/Video Tape Rental Stores', 'exacta', false, NULL),
  ('5323', 'Ecommerce - Equipment, Tool, Furniture, and Appliance Rental and Leasing', 'exacta', false, NULL),
  ('5324', 'Ecommerce - Equipment, Tool, Furniture, and Appliance Rental and Leasing', 'generica', false, NULL),
  ('5331', 'General Service - Other General Services', 'confirmar_tazapay', true, 'Arrendamiento de marcas y patentes'),
  ('5411', 'Professional Services - Legal Advices and Services', 'exacta', false, NULL),
  ('5412', 'Professional Services - Accounting, Auditing, Payroll, Bookkeeping Services', 'exacta', false, NULL),
  ('541213', 'Professional Services - Tax Preparation Services', 'exacta', false, NULL),
  ('5413', 'Professional Services - Architectural, Engineering, and Surveying Services', 'exacta', false, NULL),
  ('541320', 'Professional Service - Design & Architecture (Landscape and Horticultural Services)', 'exacta', false, NULL),
  ('541380', 'General Services - Testing Laboratories (Non - Medical Testing)', 'exacta', false, NULL),
  ('5414', 'Professional Service - Design & Architecture (Others)', 'exacta', false, NULL),
  ('541430', 'Professional Service - Freelance (Graphic Design)', 'exacta', false, NULL),
  ('541511', 'Professional Service - App/Website/Software Development & Maintenance', 'exacta', false, NULL),
  ('541512', 'Professional Service - App/Website/Software Development & Maintenance', 'exacta', false, NULL),
  ('541513', 'General Service - Computer Network/Information Services', 'generica', false, NULL),
  ('541519', 'Others - Computer Maintenance, Repair and Services (Not Elsewhere Classified)', 'generica', false, NULL),
  ('5416', 'Professional Service - Consulting & Coaching', 'exacta', false, NULL),
  ('5417', 'Professional Service - Consulting & Coaching', 'confirmar_tazapay', true, 'Investigación y desarrollo: sin vertical propio'),
  ('5418', 'Others - Online: Advertising Services', 'generica', false, NULL),
  ('541850', 'Other Offline - Offline: Advertising Services', 'exacta', false, NULL),
  ('541860', 'Other Offline - Offline: Advertising Services', 'exacta', false, NULL),
  ('541910', 'Professional Service - Customer Survey & Market Research', 'exacta', false, NULL),
  ('54192', 'General Service - Photography Studios', 'exacta', false, NULL),
  ('541930', 'Professional Service - Content Writing & Proof Reading', 'generica', false, NULL),
  ('541940', 'Medical Services - Doctors, Physicians & Vets - Veterinary Services', 'exacta', false, NULL),
  ('541990', 'Professional Service - Freelance (Others)', 'generica', false, NULL),
  ('5511', 'Financial Service - Fund, Wealth Management & Investment Holding', 'generica', true, 'Holding'),
  ('551114', 'Financial Services - Intra - Company Purchases', 'confirmar_tazapay', true, '"Intra - Company Purchases" describe un tipo de pago, no una industria'),
  ('5611', 'Professional Service - BPO & KPO', 'exacta', false, NULL),
  ('5612', 'General Services - Cleaning, Maintenance, and Janitorial Services', 'generica', false, NULL),
  ('5613', 'Professional Services - Employment Agencies and Temporary Help Services', 'exacta', false, NULL),
  ('561330', 'Software as a Service - Employer on Record', 'exacta', false, NULL),
  ('5614', 'Professional Service - BPO & KPO', 'exacta', false, NULL),
  ('561431', 'Professional Services - Courier Services - Air and Ground, and Freight Forwarders', 'generica', false, NULL),
  ('561439', 'Professional Service - Photocopying, Reproduction, and Blueprinting Services', 'exacta', false, NULL),
  ('561440', 'Financial Service - Other Financial Services (Non - classified)', 'confirmar_tazapay', true, 'Agencias de cobranza'),
  ('561450', 'Professional Service - Credit Rating & Financial Data', 'exacta', false, NULL),
  ('561491', 'General Service - Other General Services', 'generica', false, NULL),
  ('561492', 'Professional Service - Freelance (Others)', 'generica', false, NULL),
  ('561510', 'Travel & Leisure - Travel Agencies & OTAs', 'exacta', false, NULL),
  ('561520', 'Travel & Leisure - Destination Management Companies', 'generica', false, NULL),
  ('561591', 'Travel & Leisure - Destination Management Companies', 'generica', false, NULL),
  ('561599', 'Travel & Leisure - Other Travel & Booking services (e.g., Visa)', 'exacta', false, NULL),
  ('5616', 'Professional Services - Detective Agencies, Protective Services, and Security Services, including Armored Cars, and Guard Dogs', 'exacta', false, NULL),
  ('561622', 'Other Offline - Offline: Miscellaneous Repair Shops and Related Services', 'generica', false, NULL),
  ('561710', 'General Services - Exterminating and Disinfecting Services', 'exacta', false, NULL),
  ('561720', 'General Services - Cleaning, Maintenance, and Janitorial Services', 'exacta', false, NULL),
  ('561730', 'Professional Service - Design & Architecture (Landscape and Horticultural Services)', 'exacta', false, NULL),
  ('561740', 'General Services - Carpet and Upholstery Cleaning', 'exacta', false, NULL),
  ('561790', 'General Services - Cleaning, Maintenance, and Janitorial Services', 'generica', false, NULL),
  ('561910', 'General Service - Other General Services', 'generica', false, 'Servicios de empaque y etiquetado'),
  ('561920', 'General Service - Other General Services', 'generica', false, 'Organizadores de ferias y convenciones'),
  ('561990', 'General Service - Other General Services', 'generica', false, NULL),
  ('562', 'General Service - Recycling & Waste Management', 'exacta', false, NULL),
  ('6111', 'Education - Elementary and Secondary Schools', 'exacta', false, NULL),
  ('6112', 'Education - Colleges, Universities, Professional Schools, and Junior Colleges', 'exacta', false, NULL),
  ('6113', 'Education - Colleges, Universities, Professional Schools, and Junior Colleges', 'exacta', false, NULL),
  ('611410', 'Education (others) - Business and Secretarial Schools', 'exacta', false, NULL),
  ('611420', 'Education (others) - Vocational and Trade Schools', 'exacta', false, NULL),
  ('611430', 'Education (others) - Other Educational Services not elsewhere classified', 'generica', false, NULL),
  ('6115', 'Education (others) - Vocational and Trade Schools', 'exacta', false, NULL),
  ('6116', 'Education (others) - Other Educational Services not elsewhere classified', 'generica', false, NULL),
  ('611691', 'Education - Elearning, Online Tutoring, Homework & Test Prep', 'generica', false, NULL),
  ('6117', 'Education (others) - Other Educational Services not elsewhere classified', 'generica', false, NULL),
  ('6211', 'Medical Services - Doctors, Physicians & Vets - Doctors and Physicians (Not Elsewhere Classified)', 'exacta', false, NULL),
  ('6212', 'Medical Services - Doctors, Physicians & Vets - Dentists and Orthodontists', 'exacta', false, NULL),
  ('621310', 'Medical Services - Doctors, Physicians & Vets - Chiropractors', 'exacta', false, NULL),
  ('621320', 'Medical Services - Doctors, Physicians & Vets - Optometrists and Ophthalmologists', 'exacta', false, NULL),
  ('621330', 'Professional Service - Counseling Services', 'generica', false, NULL),
  ('621340', 'Medical Services - Doctors, Physicians & Vets - Doctors and Physicians (Not Elsewhere Classified)', 'generica', false, NULL),
  ('621391', 'Medical Services - Doctors, Physicians & Vets - Podiatrists and Chiropodists', 'exacta', false, NULL),
  ('621399', 'Medical Services - Doctors, Physicians & Vets - Doctors and Physicians (Not Elsewhere Classified)', 'generica', false, NULL),
  ('6214', 'Medical Services - Doctors, Physicians & Vets - Doctors and Physicians (Not Elsewhere Classified)', 'generica', false, NULL),
  ('6215', 'Medical Services - Medical and Dental Laboratories', 'exacta', false, NULL),
  ('6216', 'Medical Services - Nursing and Personal Care Facilities', 'generica', false, NULL),
  ('621910', 'Travel & Leisure - Other Transportation Services (Ambulance Services)', 'exacta', false, NULL),
  ('621991', NULL, 'sin_vertical', false, 'Bancos de sangre y órganos'),
  ('621999', 'Medical Services - Doctors, Physicians & Vets - Doctors and Physicians (Not Elsewhere Classified)', 'generica', false, NULL),
  ('622', 'Medical Services - Hospitals', 'exacta', false, NULL),
  ('623', 'Medical Services - Nursing and Personal Care Facilities', 'exacta', false, NULL),
  ('624', 'General Service - Other General Services', 'generica', false, 'Asistencia social'),
  ('6244', 'General Service - Other General Services', 'generica', false, NULL),
  ('7111', 'Other Offline - Offline: Bands, Orchestras, and Miscellaneous Entertainers (Not Elsewhere Classified)', 'exacta', false, NULL),
  ('7112', 'General Service - Membership Organizations (e.g., Professional Sports Clubs)', 'exacta', false, NULL),
  ('711212', NULL, 'no_elegible', true, 'Hipódromos: apuestas'),
  ('711219', 'General Service - Recreation Services (Not Elsewhere Classified)', 'generica', false, NULL),
  ('7113', 'Travel & Leisure - Event Ticketing', 'generica', false, NULL),
  ('7114', 'Professional Service - Freelance (Others)', 'generica', false, NULL),
  ('7115', 'Professional Service - Freelance (Others)', 'generica', false, NULL),
  ('7121', 'Travel & Leisure - Tourist Attractions (Tourist Attractions and Exhibits)', 'exacta', false, NULL),
  ('712130', 'Travel & Leisure - Tourist Attractions (Aquariums, Seaquariums, Dolphinariums, and Zoos)', 'exacta', false, NULL),
  ('713110', 'Travel & Leisure - Tourist Attractions (Amusement Parks, Circuses, Carnivals, and Fortune Tellers)', 'exacta', false, NULL),
  ('713120', 'Other Offline - Offline: Video Game Arcades/Establishments', 'exacta', false, NULL),
  ('7132', NULL, 'no_elegible', true, 'Juegos de azar: sin vertical'),
  ('713910', 'General Service - Membership Organizations (e.g., Recreation Sports Clubs)', 'generica', false, 'Clubes de golf y country clubs'),
  ('713920', 'General Service - Recreation Services (Not Elsewhere Classified)', 'generica', false, NULL),
  ('713930', 'Travel & Leisure - Marinas, Marine Service, and Supplies', 'exacta', false, NULL),
  ('713940', 'General Service - Membership Organizations (e.g., Recreation Sports Clubs)', 'generica', false, NULL),
  ('713950', 'Other Offline - Offline: Bowling Alleys', 'exacta', false, NULL),
  ('713990', 'General Service - Recreation Services (Not Elsewhere Classified)', 'generica', false, NULL),
  ('7211', 'Travel & Leisure - Accommodation (Hotels, etc)', 'exacta', false, NULL),
  ('721120', 'Travel & Leisure - Accommodation (Hotels, etc)', 'confirmar_tazapay', true, 'Hotel con casino'),
  ('721211', 'Others - Trailer Parks and Campgrounds', 'exacta', false, NULL),
  ('721214', 'General Service - Sporting and Recreational Camps', 'exacta', false, NULL),
  ('7213', 'Travel & Leisure - Accommodation (Hotels, etc)', 'generica', false, NULL),
  ('722310', 'Other Offline - Offline: Caterers', 'generica', false, NULL),
  ('722320', 'Other Offline - Offline: Caterers', 'exacta', false, NULL),
  ('722330', 'Other Offline - Offline: Fast Food Restaurants', 'generica', false, NULL),
  ('7224', 'Other Offline - Offline: Drinking Places (Alcoholic Beverages) - Bars, Taverns, Nightclubs, Cocktail Lounges, and Discotheques', 'exacta', false, NULL),
  ('722511', 'Other Offline - Offline: Eating Places and Restaurants', 'exacta', false, NULL),
  ('722513', 'Other Offline - Offline: Fast Food Restaurants', 'exacta', false, NULL),
  ('722514', 'Other Offline - Offline: Eating Places and Restaurants', 'exacta', false, NULL),
  ('722515', 'Other Offline - Offline: Fast Food Restaurants', 'exacta', false, NULL),
  ('8111', 'Other Offline - Offline: Automotive Service Shops (Non - Dealer)', 'exacta', false, NULL),
  ('811121', 'Other Offline - Offline: Automotive Body Repair Shops', 'exacta', false, NULL),
  ('811192', 'Other Offline - Offline: Car Washes', 'exacta', false, NULL),
  ('8112', 'Other Offline - Offline: Electronics Repair Shops', 'exacta', false, NULL),
  ('8113', 'Other Offline - Offline: Miscellaneous Repair Shops and Related Services', 'exacta', false, NULL),
  ('811411', 'Other Offline - Offline: Miscellaneous Repair Shops and Related Services', 'generica', false, NULL),
  ('811412', 'Other Offline - Offline: Electrical and Small Appliance Repair Shops', 'exacta', false, NULL),
  ('811420', 'Other Offline - Offline: Furniture - Reupholstery, Repair, and Refinishing', 'exacta', false, NULL),
  ('811430', 'Other Offline - Offline: Shoe Repair Shops, Shoe Shine Parlors, and Hat Cleaning Shops', 'exacta', false, NULL),
  ('811490', 'Other Offline - Offline: Miscellaneous Repair Shops and Related Services', 'exacta', false, NULL),
  ('8121', 'Other Offline - Offline: Beauty and Barber Shops', 'exacta', false, NULL),
  ('812191', 'General Service - Health and Beauty Spas', 'generica', false, NULL),
  ('812199', 'General Service - Health and Beauty Spas', 'generica', false, NULL),
  ('8122', 'Other Offline - Offline: Funeral Services and Crematories', 'exacta', false, NULL),
  ('812310', 'General Services - Laundries - Family and Commercial', 'exacta', false, NULL),
  ('812320', 'General Services - Dry Cleaners', 'exacta', false, NULL),
  ('812331', 'General Services - Laundry, Cleaning, and Garment Services', 'exacta', false, NULL),
  ('812332', 'General Services - Laundries - Family and Commercial', 'exacta', false, NULL),
  ('812910', 'General Service - Miscellaneous Personal Services (Not Elsewhere Classified)', 'generica', false, NULL),
  ('81292', 'Professional Service - Film development, photographic prints and enlargements', 'exacta', false, NULL),
  ('812930', 'Others - Parking Lots, Parking Meters and Garages', 'exacta', false, NULL),
  ('812990', 'General Service - Miscellaneous Personal Services (Not Elsewhere Classified)', 'exacta', false, NULL),
  ('8131', 'General Service - Membership Organizations (e.g., Non - sports)', 'confirmar_tazapay', true, 'Organizaciones religiosas'),
  ('8132', 'General Service - Membership Organizations (Civic, Social, and Fraternal Associations)', 'confirmar_tazapay', true, 'Fundaciones que otorgan donaciones'),
  ('8133', 'General Service - Membership Organizations (Civic, Social, and Fraternal Associations)', 'generica', false, NULL),
  ('8134', 'General Service - Membership Organizations (Civic, Social, and Fraternal Associations)', 'exacta', false, NULL),
  ('8139', 'General Service - Membership Organizations (e.g., Non - sports)', 'exacta', false, NULL),
  ('813940', 'General Service - Membership Organizations (e.g., Non - sports)', 'confirmar_tazapay', true, 'Organización política: PEP'),
  ('8141', NULL, 'no_elegible', false, 'Hogares privados: no es una empresa'),
  ('92', 'Professional Services (Govt) - Not elsewhere classified', 'confirmar_tazapay', true, 'Entidad pública: los verticales "Govt" describen pagos al Estado, no a la entidad como cliente'),
  ('921130', 'Professional Services (Govt) - Tax Payments', 'confirmar_tazapay', true, 'Entidad pública'),
  ('922110', 'Professional Services (Govt) - Court Costs, Including Alimony and Child Support', 'confirmar_tazapay', true, 'Entidad pública')
ON CONFLICT (naics_prefix) DO UPDATE SET
  vertical = EXCLUDED.vertical,
  quality = EXCLUDED.quality,
  requires_compliance = EXCLUDED.requires_compliance,
  note = EXCLUDED.note;
